site_name: approxbayescomp Python Package

nav:
  - Home: index.md
  - What is ABC?: what-is-abc.md
  - Examples:
      - Geometric-Exponential Compound Sums: geometric-exponential.ipynb
      - Frequency-Dependent Claim Sizes: frequency-dependent-claim-sizes.ipynb
      - Bivariate Observations: bivariate-observations.ipynb
      - Seasonal Claim Arrivals: seasonal-claim-arrivals.ipynb

theme:
  name: material

  icon:
    logo: material/chart-bell-curve

  palette:
    primary: teal
    accent: teal

  font:
    text: Alegreya Sans

  hljs_languages:
    - python

  custom_dir: 'docs/overrides'

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      ignore_h1_titles: False
      include_source: True
  - macros

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike