site_name: approxbayescomp

nav:
  - Home: index.md
  - What is ABC?: what-is-abc.md
  - Examples (WIP):
      # - Section 2: Section 2.ipynb
      - Geometric-Exponential Compound Sums: Section 3.1.ipynb
      # - Model Selection: Section 4.ipynb
      # - Section 5.1 Part 1: Section 5.1 Part 1.ipynb
      # - Section 5.1 Part 2: Section 5.1 Part 2.ipynb
      - Frequency-Dependent Claim Sizes: Section 5.2.ipynb
      - Multiple Claims Processes: Section 5.3.ipynb
      - Seasonal Claim Arrivals: Section 5.4.ipynb
      - Australian Auto Claims Dataset: Section 6.ipynb
      - Model Selection: Table 2.ipynb

theme:
  name: material

  palette:
    primary: teal
    accent: teal

  font:
    text: Alegreya Sans

  hljs_languages:
    - python

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      ignore_h1_titles: True
  - macros

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js