[project]
name = "approxbayescomp"
version = "0.2.1"
description = "Approximate Bayesian Computation for actuaries"
readme = "README.md"
#homepage = "https://github.com/Pat-Laub/approxbayescomp"
license = "MIT"
authors = [
    { name = "Patrick Laub", email = "patrick.laub@gmail.com" },
    { name = "Pierre-Olivier Goffard" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Intended Audience :: Science/Research"
]
dependencies = [
    "joblib",
    "numba",
    "numpy",
    "scipy",
    "tqdm",
    "matplotlib",
    "hilbertcurve"
]

[project.optional-dependencies]
dev = ["black", "build", "flake8", "pandas", "pre-commit", "pytest", "twine"]
docs = ["ipywidgets", "mike", "mkdocs",  "mkdocs-jupyter", "mkdocs-macros-plugin", "mkdocs-material", "pymc", "seaborn"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
